services:
  # NestJS Backend API Service
  api:
    image: ${API_IMAGE:-ghcr.io/gurukul-org/gurukul-monorepo/api:latest}
    container_name: gurukul_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AT_SECRET=${AT_SECRET}
      - RT_SECRET=${RT_SECRET}
      - APP_DOMAIN=${APP_DOMAIN}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}

  # Next.js Frontend Web Service
  web:
    image: ${WEB_IMAGE:-ghcr.io/gurukul-org/gurukul-monorepo/web:latest}
    container_name: gurukul_web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    depends_on:
      - api
